---

- name: Test if nomad_version is set correctly
  ansible.builtin.assert:
    that:
      - nomad_version is defined
      - nomad_version is string
    quiet: yes

- name: Test if nomad_destination is set correctly
  ansible.builtin.assert:
    that:
      - nomad_destination is defined
    quiet: yes