name: Molecule Test

on:
  push:
    branches:
      - main

jobs:
  molecule_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          pip3 install molecule[docker] ansible
      
      - name: Run Molecule Test
        run: |
          cd nomadv1
          molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'